// app/lib/countries.ts
export const EXTRA_COUNTRIES = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bangladesh", code: "BD" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR" },
  { name: "Bulgaria", code: "BG" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Czechia", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  { name: "Kenya", code: "KE" },
  { name: "Kuwait", code: "KW" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Madagascar", code: "MG" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Malta", code: "MT" },
  { name: "Mexico", code: "MX" },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nigeria", code: "NG" },
  { name: "North Korea", code: "KP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Panama", code: "PA" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Taiwan", code: "TW" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

// ISO 3166-1 alpha-2 country code -> ISO 4217 currency code
// Only primary currencies; keep it small and practical for your use case.
export const COUNTRY_TO_CURRENCY: Record<string, string> = {
  AF: "AFN",
  AL: "ALL",
  DZ: "DZD",
  AD: "EUR",
  AO: "AOA",
  AR: "ARS",
  AM: "AMD",
  AU: "AUD",
  AT: "EUR",
  AZ: "AZN",
  BD: "BDT",
  BY: "BYN",
  BE: "EUR",
  BT: "BTN",
  BO: "BOB",
  BA: "BAM",
  BW: "BWP",
  BR: "BRL",
  BG: "BGN",
  KH: "KHR",
  CM: "XAF",
  CA: "CAD",
  CL: "CLP",
  CN: "CNY",
  CO: "COP",
  CR: "CRC",
  HR: "EUR",
  CZ: "CZK",
  DK: "DKK",
  DO: "DOP",
  EC: "USD",
  EG: "EGP",
  EE: "EUR",
  ET: "ETB",
  FI: "EUR",
  FR: "EUR",
  GE: "GEL",
  DE: "EUR",
  GH: "GHS",
  GR: "EUR",
  HK: "HKD",
  HU: "HUF",
  IS: "ISK",
  IN: "INR",
  ID: "IDR",
  IR: "IRR",
  IQ: "IQD",
  IE: "EUR",
  IL: "ILS",
  IT: "EUR",
  JM: "JMD",
  JP: "JPY",
  JO: "JOD",
  KE: "KES",
  KW: "KWD",
  LA: "LAK",
  LV: "EUR",
  LB: "LBP",
  LT: "EUR",
  LU: "EUR",
  MG: "MGA",
  MY: "MYR",
  MV: "MVR",
  MT: "EUR",
  MX: "MXN",
  MD: "MDL",
  MC: "EUR",
  MN: "MNT",
  MA: "MAD",
  MZ: "MZN",
  MM: "MMK",
  NA: "NAD",
  NP: "NPR",
  NL: "EUR",
  NZ: "NZD",
  NG: "NGN",
  KP: "KPW",
  NO: "NOK",
  OM: "OMR",
  PK: "PKR",
  PA: "PAB",
  PE: "PEN",
  PH: "PHP",
  PL: "PLN",
  PT: "EUR",
  QA: "QAR",
  RO: "RON",
  RU: "RUB",
  SA: "SAR",
  SN: "XOF",
  RS: "RSD",
  SG: "SGD",
  SK: "EUR",
  SI: "EUR",
  ZA: "ZAR",
  KR: "KRW",
  ES: "EUR",
  LK: "LKR",
  SE: "SEK",
  CH: "CHF",
  TW: "TWD",
  TZ: "TZS",
  TH: "THB",
  TN: "TND",
  TR: "TRY",
  UG: "UGX",
  UA: "UAH",
  AE: "AED",
  GB: "GBP",
  US: "USD",
  UY: "UYU",
  UZ: "UZS",
  VE: "VES",
  VN: "VND",
  YE: "YER",
  ZM: "ZMW",
  ZW: "ZWL",
};

// Helper: get currency code for a given ISO country code, or null if unknown
export function getCurrencyForCountryCode(code: string): string | null {
  return COUNTRY_TO_CURRENCY[code] || null;
}
